# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matthias/repos/microtools/microtools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matthias/repos/microtools/microtools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthias/repos/microtools/microtools/CMakeFiles /home/matthias/repos/microtools/microtools//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthias/repos/microtools/microtools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named microtools.core

# Build rule for target.
microtools.core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 microtools.core
.PHONY : microtools.core

# fast build rule for target.
microtools.core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/build
.PHONY : microtools.core/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/main.cpp.s
.PHONY : main.cpp.s

microtools_development/ITK.o: microtools_development/ITK.cpp.o
.PHONY : microtools_development/ITK.o

# target to build an object file
microtools_development/ITK.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/ITK.cpp.o
.PHONY : microtools_development/ITK.cpp.o

microtools_development/ITK.i: microtools_development/ITK.cpp.i
.PHONY : microtools_development/ITK.i

# target to preprocess a source file
microtools_development/ITK.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/ITK.cpp.i
.PHONY : microtools_development/ITK.cpp.i

microtools_development/ITK.s: microtools_development/ITK.cpp.s
.PHONY : microtools_development/ITK.s

# target to generate assembly for a file
microtools_development/ITK.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/ITK.cpp.s
.PHONY : microtools_development/ITK.cpp.s

microtools_development/click.o: microtools_development/click.cpp.o
.PHONY : microtools_development/click.o

# target to build an object file
microtools_development/click.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/click.cpp.o
.PHONY : microtools_development/click.cpp.o

microtools_development/click.i: microtools_development/click.cpp.i
.PHONY : microtools_development/click.i

# target to preprocess a source file
microtools_development/click.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/click.cpp.i
.PHONY : microtools_development/click.cpp.i

microtools_development/click.s: microtools_development/click.cpp.s
.PHONY : microtools_development/click.s

# target to generate assembly for a file
microtools_development/click.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/click.cpp.s
.PHONY : microtools_development/click.cpp.s

microtools_development/hist.o: microtools_development/hist.cpp.o
.PHONY : microtools_development/hist.o

# target to build an object file
microtools_development/hist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/hist.cpp.o
.PHONY : microtools_development/hist.cpp.o

microtools_development/hist.i: microtools_development/hist.cpp.i
.PHONY : microtools_development/hist.i

# target to preprocess a source file
microtools_development/hist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/hist.cpp.i
.PHONY : microtools_development/hist.cpp.i

microtools_development/hist.s: microtools_development/hist.cpp.s
.PHONY : microtools_development/hist.s

# target to generate assembly for a file
microtools_development/hist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/hist.cpp.s
.PHONY : microtools_development/hist.cpp.s

microtools_development/in_params.o: microtools_development/in_params.cpp.o
.PHONY : microtools_development/in_params.o

# target to build an object file
microtools_development/in_params.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/in_params.cpp.o
.PHONY : microtools_development/in_params.cpp.o

microtools_development/in_params.i: microtools_development/in_params.cpp.i
.PHONY : microtools_development/in_params.i

# target to preprocess a source file
microtools_development/in_params.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/in_params.cpp.i
.PHONY : microtools_development/in_params.cpp.i

microtools_development/in_params.s: microtools_development/in_params.cpp.s
.PHONY : microtools_development/in_params.s

# target to generate assembly for a file
microtools_development/in_params.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/in_params.cpp.s
.PHONY : microtools_development/in_params.cpp.s

microtools_development/kernel/alloc.o: microtools_development/kernel/alloc.c.o
.PHONY : microtools_development/kernel/alloc.o

# target to build an object file
microtools_development/kernel/alloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/alloc.c.o
.PHONY : microtools_development/kernel/alloc.c.o

microtools_development/kernel/alloc.i: microtools_development/kernel/alloc.c.i
.PHONY : microtools_development/kernel/alloc.i

# target to preprocess a source file
microtools_development/kernel/alloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/alloc.c.i
.PHONY : microtools_development/kernel/alloc.c.i

microtools_development/kernel/alloc.s: microtools_development/kernel/alloc.c.s
.PHONY : microtools_development/kernel/alloc.s

# target to generate assembly for a file
microtools_development/kernel/alloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/alloc.c.s
.PHONY : microtools_development/kernel/alloc.c.s

microtools_development/kernel/convol.o: microtools_development/kernel/convol.c.o
.PHONY : microtools_development/kernel/convol.o

# target to build an object file
microtools_development/kernel/convol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/convol.c.o
.PHONY : microtools_development/kernel/convol.c.o

microtools_development/kernel/convol.i: microtools_development/kernel/convol.c.i
.PHONY : microtools_development/kernel/convol.i

# target to preprocess a source file
microtools_development/kernel/convol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/convol.c.i
.PHONY : microtools_development/kernel/convol.c.i

microtools_development/kernel/convol.s: microtools_development/kernel/convol.c.s
.PHONY : microtools_development/kernel/convol.s

# target to generate assembly for a file
microtools_development/kernel/convol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/convol.c.s
.PHONY : microtools_development/kernel/convol.c.s

microtools_development/kernel/correct.o: microtools_development/kernel/correct.c.o
.PHONY : microtools_development/kernel/correct.o

# target to build an object file
microtools_development/kernel/correct.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/correct.c.o
.PHONY : microtools_development/kernel/correct.c.o

microtools_development/kernel/correct.i: microtools_development/kernel/correct.c.i
.PHONY : microtools_development/kernel/correct.i

# target to preprocess a source file
microtools_development/kernel/correct.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/correct.c.i
.PHONY : microtools_development/kernel/correct.c.i

microtools_development/kernel/correct.s: microtools_development/kernel/correct.c.s
.PHONY : microtools_development/kernel/correct.s

# target to generate assembly for a file
microtools_development/kernel/correct.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/correct.c.s
.PHONY : microtools_development/kernel/correct.c.s

microtools_development/kernel/error.o: microtools_development/kernel/error.c.o
.PHONY : microtools_development/kernel/error.o

# target to build an object file
microtools_development/kernel/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/error.c.o
.PHONY : microtools_development/kernel/error.c.o

microtools_development/kernel/error.i: microtools_development/kernel/error.c.i
.PHONY : microtools_development/kernel/error.i

# target to preprocess a source file
microtools_development/kernel/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/error.c.i
.PHONY : microtools_development/kernel/error.c.i

microtools_development/kernel/error.s: microtools_development/kernel/error.c.s
.PHONY : microtools_development/kernel/error.s

# target to generate assembly for a file
microtools_development/kernel/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/error.c.s
.PHONY : microtools_development/kernel/error.c.s

microtools_development/kernel/link.o: microtools_development/kernel/link.c.o
.PHONY : microtools_development/kernel/link.o

# target to build an object file
microtools_development/kernel/link.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/link.c.o
.PHONY : microtools_development/kernel/link.c.o

microtools_development/kernel/link.i: microtools_development/kernel/link.c.i
.PHONY : microtools_development/kernel/link.i

# target to preprocess a source file
microtools_development/kernel/link.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/link.c.i
.PHONY : microtools_development/kernel/link.c.i

microtools_development/kernel/link.s: microtools_development/kernel/link.c.s
.PHONY : microtools_development/kernel/link.s

# target to generate assembly for a file
microtools_development/kernel/link.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/link.c.s
.PHONY : microtools_development/kernel/link.c.s

microtools_development/kernel/normal.o: microtools_development/kernel/normal.c.o
.PHONY : microtools_development/kernel/normal.o

# target to build an object file
microtools_development/kernel/normal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/normal.c.o
.PHONY : microtools_development/kernel/normal.c.o

microtools_development/kernel/normal.i: microtools_development/kernel/normal.c.i
.PHONY : microtools_development/kernel/normal.i

# target to preprocess a source file
microtools_development/kernel/normal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/normal.c.i
.PHONY : microtools_development/kernel/normal.c.i

microtools_development/kernel/normal.s: microtools_development/kernel/normal.c.s
.PHONY : microtools_development/kernel/normal.s

# target to generate assembly for a file
microtools_development/kernel/normal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/normal.c.s
.PHONY : microtools_development/kernel/normal.c.s

microtools_development/kernel/position.o: microtools_development/kernel/position.c.o
.PHONY : microtools_development/kernel/position.o

# target to build an object file
microtools_development/kernel/position.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/position.c.o
.PHONY : microtools_development/kernel/position.c.o

microtools_development/kernel/position.i: microtools_development/kernel/position.c.i
.PHONY : microtools_development/kernel/position.i

# target to preprocess a source file
microtools_development/kernel/position.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/position.c.i
.PHONY : microtools_development/kernel/position.c.i

microtools_development/kernel/position.s: microtools_development/kernel/position.c.s
.PHONY : microtools_development/kernel/position.s

# target to generate assembly for a file
microtools_development/kernel/position.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/position.c.s
.PHONY : microtools_development/kernel/position.c.s

microtools_development/kernel/thresh.o: microtools_development/kernel/thresh.c.o
.PHONY : microtools_development/kernel/thresh.o

# target to build an object file
microtools_development/kernel/thresh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/thresh.c.o
.PHONY : microtools_development/kernel/thresh.c.o

microtools_development/kernel/thresh.i: microtools_development/kernel/thresh.c.i
.PHONY : microtools_development/kernel/thresh.i

# target to preprocess a source file
microtools_development/kernel/thresh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/thresh.c.i
.PHONY : microtools_development/kernel/thresh.c.i

microtools_development/kernel/thresh.s: microtools_development/kernel/thresh.c.s
.PHONY : microtools_development/kernel/thresh.s

# target to generate assembly for a file
microtools_development/kernel/thresh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/thresh.c.s
.PHONY : microtools_development/kernel/thresh.c.s

microtools_development/kernel/width.o: microtools_development/kernel/width.c.o
.PHONY : microtools_development/kernel/width.o

# target to build an object file
microtools_development/kernel/width.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/width.c.o
.PHONY : microtools_development/kernel/width.c.o

microtools_development/kernel/width.i: microtools_development/kernel/width.c.i
.PHONY : microtools_development/kernel/width.i

# target to preprocess a source file
microtools_development/kernel/width.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/width.c.i
.PHONY : microtools_development/kernel/width.c.i

microtools_development/kernel/width.s: microtools_development/kernel/width.c.s
.PHONY : microtools_development/kernel/width.s

# target to generate assembly for a file
microtools_development/kernel/width.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/kernel/width.c.s
.PHONY : microtools_development/kernel/width.c.s

microtools_development/menu.o: microtools_development/menu.cpp.o
.PHONY : microtools_development/menu.o

# target to build an object file
microtools_development/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/menu.cpp.o
.PHONY : microtools_development/menu.cpp.o

microtools_development/menu.i: microtools_development/menu.cpp.i
.PHONY : microtools_development/menu.i

# target to preprocess a source file
microtools_development/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/menu.cpp.i
.PHONY : microtools_development/menu.cpp.i

microtools_development/menu.s: microtools_development/menu.cpp.s
.PHONY : microtools_development/menu.s

# target to generate assembly for a file
microtools_development/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/menu.cpp.s
.PHONY : microtools_development/menu.cpp.s

microtools_development/misc.o: microtools_development/misc.cpp.o
.PHONY : microtools_development/misc.o

# target to build an object file
microtools_development/misc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/misc.cpp.o
.PHONY : microtools_development/misc.cpp.o

microtools_development/misc.i: microtools_development/misc.cpp.i
.PHONY : microtools_development/misc.i

# target to preprocess a source file
microtools_development/misc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/misc.cpp.i
.PHONY : microtools_development/misc.cpp.i

microtools_development/misc.s: microtools_development/misc.cpp.s
.PHONY : microtools_development/misc.s

# target to generate assembly for a file
microtools_development/misc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/misc.cpp.s
.PHONY : microtools_development/misc.cpp.s

microtools_development/out_params.o: microtools_development/out_params.cpp.o
.PHONY : microtools_development/out_params.o

# target to build an object file
microtools_development/out_params.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/out_params.cpp.o
.PHONY : microtools_development/out_params.cpp.o

microtools_development/out_params.i: microtools_development/out_params.cpp.i
.PHONY : microtools_development/out_params.i

# target to preprocess a source file
microtools_development/out_params.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/out_params.cpp.i
.PHONY : microtools_development/out_params.cpp.i

microtools_development/out_params.s: microtools_development/out_params.cpp.s
.PHONY : microtools_development/out_params.s

# target to generate assembly for a file
microtools_development/out_params.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/out_params.cpp.s
.PHONY : microtools_development/out_params.cpp.s

microtools_development/program.o: microtools_development/program.cpp.o
.PHONY : microtools_development/program.o

# target to build an object file
microtools_development/program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/program.cpp.o
.PHONY : microtools_development/program.cpp.o

microtools_development/program.i: microtools_development/program.cpp.i
.PHONY : microtools_development/program.i

# target to preprocess a source file
microtools_development/program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/program.cpp.i
.PHONY : microtools_development/program.cpp.i

microtools_development/program.s: microtools_development/program.cpp.s
.PHONY : microtools_development/program.s

# target to generate assembly for a file
microtools_development/program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/program.cpp.s
.PHONY : microtools_development/program.cpp.s

microtools_development/quality.o: microtools_development/quality.cpp.o
.PHONY : microtools_development/quality.o

# target to build an object file
microtools_development/quality.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/quality.cpp.o
.PHONY : microtools_development/quality.cpp.o

microtools_development/quality.i: microtools_development/quality.cpp.i
.PHONY : microtools_development/quality.i

# target to preprocess a source file
microtools_development/quality.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/quality.cpp.i
.PHONY : microtools_development/quality.cpp.i

microtools_development/quality.s: microtools_development/quality.cpp.s
.PHONY : microtools_development/quality.s

# target to generate assembly for a file
microtools_development/quality.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/quality.cpp.s
.PHONY : microtools_development/quality.cpp.s

microtools_development/ridge.o: microtools_development/ridge.cpp.o
.PHONY : microtools_development/ridge.o

# target to build an object file
microtools_development/ridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/ridge.cpp.o
.PHONY : microtools_development/ridge.cpp.o

microtools_development/ridge.i: microtools_development/ridge.cpp.i
.PHONY : microtools_development/ridge.i

# target to preprocess a source file
microtools_development/ridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/ridge.cpp.i
.PHONY : microtools_development/ridge.cpp.i

microtools_development/ridge.s: microtools_development/ridge.cpp.s
.PHONY : microtools_development/ridge.s

# target to generate assembly for a file
microtools_development/ridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/ridge.cpp.s
.PHONY : microtools_development/ridge.cpp.s

microtools_development/segment.o: microtools_development/segment.cpp.o
.PHONY : microtools_development/segment.o

# target to build an object file
microtools_development/segment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/segment.cpp.o
.PHONY : microtools_development/segment.cpp.o

microtools_development/segment.i: microtools_development/segment.cpp.i
.PHONY : microtools_development/segment.i

# target to preprocess a source file
microtools_development/segment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/segment.cpp.i
.PHONY : microtools_development/segment.cpp.i

microtools_development/segment.s: microtools_development/segment.cpp.s
.PHONY : microtools_development/segment.s

# target to generate assembly for a file
microtools_development/segment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/segment.cpp.s
.PHONY : microtools_development/segment.cpp.s

microtools_development/stabilize.o: microtools_development/stabilize.cpp.o
.PHONY : microtools_development/stabilize.o

# target to build an object file
microtools_development/stabilize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/stabilize.cpp.o
.PHONY : microtools_development/stabilize.cpp.o

microtools_development/stabilize.i: microtools_development/stabilize.cpp.i
.PHONY : microtools_development/stabilize.i

# target to preprocess a source file
microtools_development/stabilize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/stabilize.cpp.i
.PHONY : microtools_development/stabilize.cpp.i

microtools_development/stabilize.s: microtools_development/stabilize.cpp.s
.PHONY : microtools_development/stabilize.s

# target to generate assembly for a file
microtools_development/stabilize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/stabilize.cpp.s
.PHONY : microtools_development/stabilize.cpp.s

microtools_development/track.o: microtools_development/track.cpp.o
.PHONY : microtools_development/track.o

# target to build an object file
microtools_development/track.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/track.cpp.o
.PHONY : microtools_development/track.cpp.o

microtools_development/track.i: microtools_development/track.cpp.i
.PHONY : microtools_development/track.i

# target to preprocess a source file
microtools_development/track.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/track.cpp.i
.PHONY : microtools_development/track.cpp.i

microtools_development/track.s: microtools_development/track.cpp.s
.PHONY : microtools_development/track.s

# target to generate assembly for a file
microtools_development/track.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/track.cpp.s
.PHONY : microtools_development/track.cpp.s

microtools_development/vessel.o: microtools_development/vessel.cpp.o
.PHONY : microtools_development/vessel.o

# target to build an object file
microtools_development/vessel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/vessel.cpp.o
.PHONY : microtools_development/vessel.cpp.o

microtools_development/vessel.i: microtools_development/vessel.cpp.i
.PHONY : microtools_development/vessel.i

# target to preprocess a source file
microtools_development/vessel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/vessel.cpp.i
.PHONY : microtools_development/vessel.cpp.i

microtools_development/vessel.s: microtools_development/vessel.cpp.s
.PHONY : microtools_development/vessel.s

# target to generate assembly for a file
microtools_development/vessel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/vessel.cpp.s
.PHONY : microtools_development/vessel.cpp.s

microtools_development/video.o: microtools_development/video.cpp.o
.PHONY : microtools_development/video.o

# target to build an object file
microtools_development/video.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/video.cpp.o
.PHONY : microtools_development/video.cpp.o

microtools_development/video.i: microtools_development/video.cpp.i
.PHONY : microtools_development/video.i

# target to preprocess a source file
microtools_development/video.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/video.cpp.i
.PHONY : microtools_development/video.cpp.i

microtools_development/video.s: microtools_development/video.cpp.s
.PHONY : microtools_development/video.s

# target to generate assembly for a file
microtools_development/video.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/microtools.core.dir/build.make CMakeFiles/microtools.core.dir/microtools_development/video.cpp.s
.PHONY : microtools_development/video.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... microtools.core"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... microtools_development/ITK.o"
	@echo "... microtools_development/ITK.i"
	@echo "... microtools_development/ITK.s"
	@echo "... microtools_development/click.o"
	@echo "... microtools_development/click.i"
	@echo "... microtools_development/click.s"
	@echo "... microtools_development/hist.o"
	@echo "... microtools_development/hist.i"
	@echo "... microtools_development/hist.s"
	@echo "... microtools_development/in_params.o"
	@echo "... microtools_development/in_params.i"
	@echo "... microtools_development/in_params.s"
	@echo "... microtools_development/kernel/alloc.o"
	@echo "... microtools_development/kernel/alloc.i"
	@echo "... microtools_development/kernel/alloc.s"
	@echo "... microtools_development/kernel/convol.o"
	@echo "... microtools_development/kernel/convol.i"
	@echo "... microtools_development/kernel/convol.s"
	@echo "... microtools_development/kernel/correct.o"
	@echo "... microtools_development/kernel/correct.i"
	@echo "... microtools_development/kernel/correct.s"
	@echo "... microtools_development/kernel/error.o"
	@echo "... microtools_development/kernel/error.i"
	@echo "... microtools_development/kernel/error.s"
	@echo "... microtools_development/kernel/link.o"
	@echo "... microtools_development/kernel/link.i"
	@echo "... microtools_development/kernel/link.s"
	@echo "... microtools_development/kernel/normal.o"
	@echo "... microtools_development/kernel/normal.i"
	@echo "... microtools_development/kernel/normal.s"
	@echo "... microtools_development/kernel/position.o"
	@echo "... microtools_development/kernel/position.i"
	@echo "... microtools_development/kernel/position.s"
	@echo "... microtools_development/kernel/thresh.o"
	@echo "... microtools_development/kernel/thresh.i"
	@echo "... microtools_development/kernel/thresh.s"
	@echo "... microtools_development/kernel/width.o"
	@echo "... microtools_development/kernel/width.i"
	@echo "... microtools_development/kernel/width.s"
	@echo "... microtools_development/menu.o"
	@echo "... microtools_development/menu.i"
	@echo "... microtools_development/menu.s"
	@echo "... microtools_development/misc.o"
	@echo "... microtools_development/misc.i"
	@echo "... microtools_development/misc.s"
	@echo "... microtools_development/out_params.o"
	@echo "... microtools_development/out_params.i"
	@echo "... microtools_development/out_params.s"
	@echo "... microtools_development/program.o"
	@echo "... microtools_development/program.i"
	@echo "... microtools_development/program.s"
	@echo "... microtools_development/quality.o"
	@echo "... microtools_development/quality.i"
	@echo "... microtools_development/quality.s"
	@echo "... microtools_development/ridge.o"
	@echo "... microtools_development/ridge.i"
	@echo "... microtools_development/ridge.s"
	@echo "... microtools_development/segment.o"
	@echo "... microtools_development/segment.i"
	@echo "... microtools_development/segment.s"
	@echo "... microtools_development/stabilize.o"
	@echo "... microtools_development/stabilize.i"
	@echo "... microtools_development/stabilize.s"
	@echo "... microtools_development/track.o"
	@echo "... microtools_development/track.i"
	@echo "... microtools_development/track.s"
	@echo "... microtools_development/vessel.o"
	@echo "... microtools_development/vessel.i"
	@echo "... microtools_development/vessel.s"
	@echo "... microtools_development/video.o"
	@echo "... microtools_development/video.i"
	@echo "... microtools_development/video.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

